apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: clientes-api
  description: Microservicio API de clientes
  annotations:
    github.com/project-slug: platform-001/micro-16
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: clientes
  providesApis:
    - api-clientes
  dependsOn:
    - resource:default/clientes-namespace
